name: 'mac and windows nightly build'

# **What it does**: Generate unsigned macOS app and installer artifacts.
# **Why we have it**: To build nightlies.
# **Who does it impact**: Release/test.

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      provider_name:
        description: 'The name of the providers branding that needs to be applied to the GUI app'
        required: true
        default: 'riseup'
        type: choice
        options:
          - riseup
          - calyx
          - floatdemo
          - demolib

  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '* 0 * * 0'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-win:
    runs-on:
      - windows-2019
    steps:
      - name: Setup Golang 1.22
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - name: Install build dependencies from chocolatey
        run: choco install qt5-default mingw sigcheck qt-installer-framework
      - run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: make curl sed
      - name: Set requested provider name
        run: sed -i.bak 's/provider = riseup/provider = ${{ inputs.provider_name }}/1' providers/vendor.conf
      - name: Build app
        run: |
          $env:PATH="$env:SystemDrive\Qt\5.15.2\mingw81_64\bin;$env:SystemDrive\Qt\QtIFW-4.4.2\bin;$env:PATH"
          echo $env:PATH
          make build
          make installer
      - name: Upload build/qt/release/riseup-vpn.exe
        uses: actions/upload-artifact@v3
        with:
          name: riseup-vpn-exe-${{ github.sha }}
          path: build/qt/release/riseup-vpn.exe
      - name: Upload build/installer/RiseupVPN-installer-*.exe
        uses: actions/upload-artifact@v3
        with:
          name: riseup-vpn-installer-${{ github.sha }}
          path: build/installer/*.exe

  build-mac:
    runs-on:
    - macos-12
    steps:
      - name: Setup Golang 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: go version
      - name: Install build dependencies from brew
        run: brew install python make create-dmg pipx
      - name: Install aqt installer
        run: pipx install aqtinstall
      - name: Setup Qt6 using aqt
        run: aqt install-qt mac desktop 6.6.2 clang_64 -O ~/Qt6
      - name: Install Qt installer framework
        run: >
          cd /tmp &&
          curl -LO https://download.qt.io/official_releases/qt-installer-framework/4.7.0/QtInstallerFramework-macOS-x64-4.7.0.dmg &&
          hdiutil attach QtInstallerFramework-macOS-x64-4.7.0.dmg &&
          cd /Volumes/QtInstallerFramework-macOS-x64-4.7.0/QtInstallerFramework-macOS-x64-4.7.0.app/Contents/MacOS &&
          ./QtInstallerFramework-macOS-x64-4.7.0 in --da -c --al
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Set requested provider name
        run: make vendor
      - name: Build .app
        run: PATH="~/Qt6/6.6.2/macos/bin:~/Qt/QtIFW-4.7.0/bin:$PATH" make QMAKE=qmake6 build
      - name: Build installer
        run: PATH="~/Qt6/6.6.2/macos/bin:~/Qt/QtIFW-4.7.0/bin:$PATH" make QMAKE=qmake6 installer
      - name: Upload build/qt/release/riseup-vpn.app
        uses: actions/upload-artifact@v4
        with:
          name: riseup-vpn-app-${{ github.sha }}
          path: build/qt/release/riseup-vpn.app
